core/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from . import views

app_name = "core"

urlpatterns = [
    path("", views.home, name="home"),
    path("check/", views.check, name="check"),
    path("maybe/", views.maybe, name="maybe"),
    path("month_charts/", csrf_exempt(views.month_charts), name="month_charts"),
    # path("inc_chart/", csrf_exempt(views.inc_chart), name="inc_chart"),
]

expenses/urls.py
from django.urls import path
from . import views

app_name = "expenses"

urlpatterns = [
    path("", views.home, name="home"),
    path("add", views.add, name="add"),
    path("<int:id>/edit", views.edit, name="edit"),
    path("<int:id>/delete", views.delete, name="delete"),
    path("add_category", views.add_category, name="add_category"),
]

expensetracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("expenses/", include("expenses.urls")),
    path("income/", include("income.urls")),
    path("reports/", include("reports.urls")),
    path("settings/", include("preferences.urls")),
    path("auth/", include("authentication.urls")),
]

income/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from . import views

app_name = "income"

urlpatterns = [
    path("", views.home, name="home"),
    # path("", csrf_exempt(views.home), name="home"),
    path("add", views.add, name="add"),
    path("<int:id>/edit", views.edit, name="edit"),
    path("<int:id>/delete", views.delete, name="delete"),
    path("add_category", views.add_category, name="add_category"),
    path("search", csrf_exempt(views.search), name="search"),
]

preferences/urls.py
from django.urls import path
from . import views

app_name = "preference"

urlpatterns = [
    path("", views.home, name="home"),
]

reports/urls.py
from django.urls import path
from . import views

app_name = "reports"

urlpatterns = [
    path("", views.home, name="home"),
]

core/views.py
from django.shortcuts import render
from django.db.models import Q
from django.http import JsonResponse, HttpResponse
from expenses.models import Expense, Category
from income.models import Income, Source
import json, calendar
import pandas as pd


# utility functions
def expense_data(u):
    exp = pd.DataFrame(list(Expense.objects.filter(user=u).values()))
    if not exp.empty:
        cat = pd.DataFrame(list(Category.objects.all().values()))
        exp["expense_date"] = pd.to_datetime(exp['expense_date'])
        exp_data = exp.merge(cat, left_on="category_id", right_on="id", suffixes=('', '_y'))
        exp_data = exp_data.drop('id_y', axis=1)
        exp_data["month"] = exp_data["expense_date"].dt.month
        exp_data["year"] = exp_data["expense_date"].dt.year
        return exp_data
    return exp


def income_data(u):
    inc = pd.DataFrame(list(Income.objects.filter(user=u).values()))
    if not inc.empty:
        src = pd.DataFrame(list(Source.objects.all().values()))
        inc["income_date"] = pd.to_datetime(inc['income_date'])
        inc_data = inc.merge(src, left_on="source_id", right_on="id", suffixes=('', '_y'))
        inc_data = inc_data.drop('id_y', axis=1)
        inc_data["month"] = inc_data["income_date"].dt.month
        inc_data["year"] = inc_data["income_date"].dt.year
        return inc_data
    return inc
    

# route functions
def home(req):
    context = {"current_page": "Home"}
    if req.user.is_authenticated:
        # get months for chart filtering
        exp = expense_data(req.user)
        emonths = [m for m in exp["month"]] if not exp.empty else []
        inc = income_data(req.user)
        imonths = [m for m in inc["month"]] if not inc.empty else []
        months = list(set(emonths + imonths))
        if months:
            months.sort()
            month_select = [{"num": m, "month_name": calendar.month_name[m]} for m in months]
            context |= {"months": month_select}
        else:
            context |= {"nodata": True}
    return render(req, "core/home.html", context)


def month_charts(req):
    context = {}

    exp = expense_data(req.user)
    inc = income_data(req.user)
    if not exp.empty:
        exp = exp[exp["user_id"] == req.user.id]
        if req.method == "POST" and int(req.POST.get("month", 0)[0]) != 0:
            # filter if month
            m = int(req.POST.get("month", 0)[0])
            exp = exp[exp["month"] == m]
        exp = exp[["name", "amount"]]
        exp = exp.groupby(["name"]).sum().sort_values(by="amount", ascending=False)
        exp_chart = {}
        exp_chart["labels"] = exp.index.tolist()
        exp_chart["values"] = exp["amount"].tolist()
        exp_chart["total"] = exp["amount"].sum()
        exp_chart["currency"] = req.user.preference.currency
        context["exp_chart"] = exp_chart
    else:
        context["exp_chart"] = False

    if not inc.empty:
        inc = inc[inc["user_id"] == req.user.id]
        if req.method == "POST" and int(req.POST.get("month", 0)[0]) != 0:
            # filter if month
            m = int(req.POST.get("month", 0)[0])
            inc = inc[inc["month"] == m]
        inc = inc[["name", "amount"]]
        inc = inc.groupby(["name"]).sum().sort_values(by="amount", ascending=False)
        inc_chart = {}
        inc_chart["labels"] = inc.index.tolist()
        inc_chart["values"] = inc["amount"].tolist()
        inc_chart["total"] = inc["amount"].sum()
        inc_chart["currency"] = req.user.preference.currency
        context["inc_chart"] = inc_chart
    else:
        context["inc_chart"] = False

    return JsonResponse(context)


def search(req):
    if req.method == "POST":
        search = json.loads(req.body).get("search")
        if search:
            # search through expenses
            expenses = Expense.objects.filter(user=req.user)
            exp_results = expenses.filter(
                Q(amount__icontains=search) | 
                Q(category__icontains=search) | 
                Q(description__icontains=search)
            )
            return JsonResponse(list(exp_results.values()), safe=False)
        
def maybe(req):
    res = f"<p>{req.user}</p>"
    res += f"<p>{req.user.is_authenticated}</p>"
    return HttpResponse(res)


def check(req):
    res = f"<h3>{Source.objects.model._meta.db_table}</h3>"
    res += "<ul>"
    res += "".join([f"<li>{f.name}</li>" for f in Source._meta.get_fields()])
    res += "</ul>"
    res += f"<h3>Expenses</h3>"
    res += "<ul>"
    res += "".join([f"<li>{f.name}: {f.expenses.count()}</li>" for f in Category.objects.all()])
    res += "</ul>"
    res += f"<h3>Expenses{req.user.preference.currency}</h3>"
    res += expense_data(req.user).to_html()
    res += income_data(req.user).to_html()
    inc = income_data(req.user)
    inc= inc[inc["month"] == 5]
    res += inc.to_html()
    return HttpResponse(res)

core/templates/core/_breadcrumb.html
<nav aria-label="breadcrumb" class="mt-2">
    <ol class="breadcrumb">
      {% for link in backlinks %}
      <li class="breadcrumb-item"><a href="{% url link.url %}">{{ link.label }}</a></li>
      {% endfor %}
      <li class="breadcrumb-item active" aria-current="page">{{ current_page }}</li>
    </ol>
  </nav>
  

core/templates/core/_messages.html
{% if messages %}
<div class="messages">
    {% for message in messages %}
    <p{% if message.tags %} class="mt-3 alert alert-dismissible alert-sm alert-{{ message.tags }}" role="alert"{% endif %}>
        <span>{{ message }}</span>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </p>
    {% endfor %}
</div>
{% endif %}

core/templates/core/_nav.html
<header class="navbar sticky-top bg-dark flex-md-nowrap p-0 shadow" data-bs-theme="dark">
    <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6 text-white" href="#">Company name</a>
  
    <ul class="navbar-nav flex-row d-md-none">
      <li class="nav-item text-nowrap">
        <button class="nav-link px-3 text-white" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSearch" aria-controls="navbarSearch" aria-expanded="false" aria-label="Toggle search">
          <svg class="bi"><use xlink:href="#search"/></svg>
        </button>
      </li>
      <li class="nav-item text-nowrap">
        <button class="nav-link px-3 text-white" type="button" data-bs-toggle="offcanvas" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
          <svg class="bi"><use xlink:href="#list"/></svg>
        </button>
      </li>
    </ul>
  
    <div id="navbarSearch" class="navbar-search w-100 collapse">
      <input class="form-control w-100 rounded-0 border-0" type="text" placeholder="Search" aria-label="Search">
    </div>
  </header>
  

core/templates/core/_nav2.html
<nav class="navbar navbar-expand-lg sticky-top bg-dark flex-md-nowrap p-0 shadow" data-bs-theme="dark">
    <div class="container-fluid">
      <a class="navbar-brand px-2" href="{% url "core:home" %}">Expense Tracker</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% if not request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link{% if page == "register" %} active{% endif %}" aria-current="page" href="{% url "auth:register" %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link{% if page == "login" %} active{% endif %}" aria-current="page" href="{% url "auth:login" %}">Log in</a>
          </li>
          {% endif %}
          {% if False %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Dropdown
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <span class="nav-link">Hi, {{ request.user.username }}.</span> 
          </li>
          {% endif %}
        </ul>
          {% if request.user.is_authenticated %}
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" id="searchField">
          <button class="btn btn-outline-secondary" type="submit">Search</button>
        </form>
           {% endif %}
     </div>
    </div>
  </nav>

core/templates/core/_nav3.html
<nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
    <div class="container-fluid">
      <a class="navbar-brand px-2" href="{% url "core:home" %}">Expense Tracker</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarColor02">
        <ul class="navbar-nav me-auto">
          {% if not request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link{% if page == "register" %} active{% endif %}" aria-current="page" href="{% url "auth:register" %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link{% if page == "login" %} active{% endif %}" aria-current="page" href="{% url "auth:login" %}">Log in</a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="#">Features</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Pricing</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">About</a>
          </li>
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Dropdown
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
          {% endif %}
        </ul>
        <form class="d-flex">
          <input class="form-control me-sm-2" type="search" placeholder="Search">
          <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>

core/templates/core/_sidebar.html
<div class="sidebar border border-right col-md-3 col-lg-2 p-0 bg-body-tertiary">
    <div class="offcanvas-md offcanvas-end bg-body-tertiary" tabindex="-1" id="sidebarMenu" aria-labelledby="sidebarMenuLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="sidebarMenuLabel">Expense Tracker</h5>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" data-bs-target="#sidebarMenu" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body d-md-flex flex-column p-0 pt-lg-3 overflow-y-auto">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link d-flex align-items-center gap-2{% if request.resolver_match.namespace == "core" %} active{% endif %}" aria-current="page" href="{% url "core:home" %}">
              <svg class="bi"><use xlink:href="#house-fill"/></svg>
              Dashboard
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link d-flex align-items-center gap-2{% if request.resolver_match.namespace == "expenses" %} active{% endif %}" href="{% url "expenses:home" %}">
              <svg class="bi"><use xlink:href="#cash-coin"/></svg>
              Expenses
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link d-flex align-items-center gap-2{% if request.resolver_match.namespace == "income" %} active{% endif %}" href="{% url "income:home" %}">
              <svg class="bi"><use xlink:href="#bank"/></svg>
              Income
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link d-flex align-items-center gap-2{% if request.resolver_match.namespace == "reports" %} active{% endif %}" href="{% url "reports:home" %}">
              <svg class="bi"><use xlink:href="#graph-up"/></svg>
              Reports
            </a>
          </li>
        </ul>
<!--
        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-body-secondary text-uppercase">
          <span>Saved reports</span>
          <a class="link-secondary" href="#" aria-label="Add a new report">
            <svg class="bi"><use xlink:href="#plus-circle"/></svg>
          </a>
        </h6>
        <ul class="nav flex-column mb-auto">
          <li class="nav-item">
            <a class="nav-link d-flex align-items-center gap-2" href="#">
              <svg class="bi"><use xlink:href="#file-earmark-text"/></svg>
              Current month
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link d-flex align-items-center gap-2" href="#">
              <svg class="bi"><use xlink:href="#file-earmark-text"/></svg>
              Last quarter
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link d-flex align-items-center gap-2" href="#">
              <svg class="bi"><use xlink:href="#file-earmark-text"/></svg>
              Social engagement
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link d-flex align-items-center gap-2" href="#">
              <svg class="bi"><use xlink:href="#file-earmark-text"/></svg>
              Year-end sale
            </a>
          </li>
        </ul>
-->
        <hr class="my-3">

        <ul class="nav flex-column mb-auto">
          <li class="nav-item">
            <a class="nav-link d-flex align-items-center gap-2{% if request.resolver_match.namespace == "preference" %} active{% endif %}" href="{% url "preference:home" %}">
              <svg class="bi"><use xlink:href="#gear-wide-connected"/></svg>
              Settings
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link d-flex align-items-center gap-2" href="{% url "auth:logout" %}">
              <svg class="bi"><use xlink:href="#door-closed"/></svg>
              Sign out
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>

core/templates/core/base.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="auto">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Expense Tracker {% block title %}{% endblock title %}</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" type="text/css" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.min.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/main.css" %}">
    
    <!-- Custom styles for this template -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.min.css" rel="stylesheet" type="text/css">
    <!-- Custom styles for this template -->
    <link href="{% static "css/dashboard.css" %}" rel="stylesheet" type="text/css">
  </head>
  <body>
{% include "core/_icons.html" %}
{% include "core/_nav2.html" %}
<div class="container-fluid">
  <div class="row">

    {% if request.user.is_authenticated %}
      {% include "core/_sidebar.html" %}
    {% endif %}

    {% block main %}
    {% endblock main %}

    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" type="text/javascript"></script>
<script src="{% static "js/color-modes.js" %}" type="text/javascript"></script>

</body>
</html>

core/templates/core/home.html
{% extends "core/base.html" %}
{% load static %}
{% block title %}- {{ current_page }}{% endblock title %}
{% block main %}
{% if request.user.is_authenticated %}
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
  {% include "core/_messages.html" %}
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Dashboard</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
      {% if not nodata %}
        <div class="form-group mt-3">
            <div class="input-group">
                <select class="form-select" name="month" id="month">
                    <option value="0">All Months</option>
                    {% for month in months %}
                    <option value="{{ month.num }}">{{ month.month_name }}</option>
                    {% endfor %}
                </select>
                <button class="btn btn-outline-primary" type="button" id="submitMonth">Select Month</button>
            </div>
          </div>
      {% endif %}
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <h3><a href="{% url "expenses:home" %}" class="link-underline link-underline-opacity-0">Expenses</a></h3>
      <div id="exp_cont"></div>
    </div>
    <div class="col-md-6">
      <h3><a href="{% url "income:home" %}" class="link-underline link-underline-opacity-0">Income</a></h3>
      <div id="inc_cont"></div>
    </div>
  </div>
  <div class="card">
      <div class="card-body">
          <div class="row align-items-center">
            <h5 class="text-muted fw-normal mt-0 text-truncate text-center" id="totaltitle"></h5>
            <h3 class="my-2 py-1 text-center" id="totaldisplay"></h3>
            <p class="mb-0 text-muted">
                <span class="text-success me-2"><i class="fa-solid fa-arrow-trend-up"></i></span>
            </p>
          </div> <!-- end row-->
      </div> <!-- end card-body -->
  </div> <!-- end card -->

</main>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.3.2/dist/chart.umd.js" integrity="sha384-eI7PSr3L1XLISH8JdDII5YN/njoSsxfbrkCTnJrzXt+ENP5MOVBxD+l6sEG4zoLp" crossorigin="anonymous"></script>
<script src="{% static "js/dash.js" %}" type="text/javascript"></script>
{% else %}
<main class="col-md-6 ms-sm-auto col-lg-8 px-md-4">
  <h2 class="mt-5">Welcome to expense tracker</h2>
  <p>Please <a href="{% url "auth:register" %}">register an account</a> to use the service.</p>
  <p>If you already have an account, please <a href="{% url "auth:login" %}">log in</a>.</p>
</main>
<div class="col-md-3 col-lg-2"></div>
{% endif %}
{% endblock main %}